### PR TITLE
Alternate solution for #6

### PR DESCRIPTION
**Pull request by sgourichon**
Based on your solution, tried to simplify/clarify. Not claiming it's really much better, though. Perhaps using closures instead of global variables would actually be better. What do you think ?

### CODE REVIEW

**Comment by nullEuro** [comment]
Yes, if the state changes fast enough the sleep is unnecessary or can be shorter. The problem is, that without the `sleep()` call the behavior of the program depends on how fast the CPU is, which is not good. On a fast machine where `on_port_change()` is faster executed than the states are "bouncing" the event queue will drain between the state changes. 

I want to keep the more flexible solution with `sleep()` but we can discuss a better value for `debounceTime` (I don't have a sound card which produces bouncing so I can't test this).

**Comment by sgourichon** [comment]
> without the sleep() call the behavior of the program depends on how fast the CPU is, which is not good.

That is just a hint, not a strong constraint. The importance of this hint depends on the actual goal.

> On a fast machine where on_port_change() is faster executed than the states are "bouncing" the event queue will drain between the state changes. 

If the goal is "don't loop after events have stopped", the sleep is unnecessary.

If the goal is "try really hard to debounce even if user wouldn't even notice" the sleep is needed. But do we need that ?

The trouble with the latter approach is IMHO it tries too hard and forces _every user_ to wait for an added latency _every times_ just to handle a corner case.

**Comment by nullEuro** [comment]
> The trouble with the latter approach is IMHO it tries too hard and forces every user to wait for an added latency every times just to handle a corner case.

Yes that is true, I though of a `debouncing=False|True` flag which can be set in the config file (defaulting to false). 

The problem is that I don't think the state is bouncing instantly filling the event queue with more than one event at a time. Imagine the following case:

The user plugs in the headphones. Pulseaudio pushes an `ActivePortChanged` event to the gObject mainloop. The mainloop executes apply-equalizers' `on_port_change()` method. Since this function basically only set one variable it finishes in a few milliseconds and the mainloop calls the `burst_end()` because the event queue is drained. Because the users' buggy hardware produces bouncing another `ActivePortChanged` event is oushed to the queue...

To minimize the delay we can reduce `debounceTime` dramatically, bouncing should take way under 500ms. I think 50ms is a good choice

**Comment by sgourichon** [comment]
> To minimize the delay we can reduce debounceTime dramatically, bouncing should take way under 500ms. I think 50ms is a good choice

Yes let's keep it small and simple and go for 50ms.

**Pull request closed without merging**
